---
- name: Ensure LIO packages are installed
  yum:
    name: targetcli
    state: present

- name: Set hostname to iscsi
  hostname:
    name: iscsi

- name: Update /etc/hosts with new hostname
  lineinfile:
    path: /etc/hosts
    regexp: '^(127\.0\.1\.1\s+).*'
    line: '127.0.1.1   iscsi'
    state: present

- name: Create partition on /dev/vdb
  parted:
    device: /dev/vdb
    number: 1
    part_type: primary
    state: present
    part_start: "0%"
    part_end: "100%"
    unit: "%"
    
- name: Create partition on /dev/vdb
  parted:
    device: /dev/vdb
    number: 1
    part_type: primary
    state: present
    part_start: "0%"
    part_end: "100%"
    unit: "%"

- name: Wait for the partition to be available
  command: udevadm settle
  become: yes

- name: Create filesystem on /dev/vdb1
  command: mkfs.ext4 /dev/vdb1
  become: yes
  #when: fs_check.rc != 0

  
- name: Check if block backstore exists
  command: targetcli ls backstores/block
  register: block_backstore_check
  ignore_errors: yes
  become: yes

- name: Create block backstore in LIO
  command: targetcli /backstores/block create name=disk0 dev=/dev/vdb1
  become: yes
  when: "'disk0' not in block_backstore_check.stdout"

- name: Create iSCSI target in LIO
  command: targetcli /iscsi create iqn.2024-06.com.example:storage.target1
  become: yes

- name: Create LUN in LIO
  command: targetcli /iscsi/iqn.2024-06.com.example:storage.target1/tpg1/luns create /backstores/block/disk0
  become: yes

- name: Set authentication (example)
  command: targetcli /iscsi/iqn.2024-06.com.example:storage.target1/tpg1 set attribute authentication=0
  become: yes

- name: Set ALC1 (example)
  command: targetcli /iscsi/iqn.2024-06.com.example:storage.target1/tpg1/acls create iqn.2024-06.com.example:node1.11111111
  become: yes

- name: Set ALC2
  command: targetcli  /iscsi/iqn.2024-06.com.example:storage.target1/tpg1/acls  create iqn.2024-06.com.example:node2.22222222
  become: yes

- name: Set ALC3
  command: targetcli  /iscsi/iqn.2024-06.com.example:storage.target1/tpg1/acls  create iqn.2024-06.com.example:node3.33333333
  become: yes

- name: Save LIO configuration
  command: targetcli saveconfig
  become: yes
